[build-system]
requires = [
    "setuptools >=44",
    "wheel >=0.36",
    "torch >=1.11",
    "rascaline @ git+https://github.com/Luthaf/rascaline.git@alchemy-paper",
    "cmake",
]
build-backend = "setuptools.build_meta"

[tool.tox]
legacy_tox_ini = """
[tox]

[testenv]
skip_install = True
deps =
    discover
    ase
    torch >=1.11
    rascaline @ git+https://github.com/Luthaf/rascaline.git@alchemy-paper

commands =
    python setup.py --quiet install
    discover -p "*.py" -s tests
"""
