[build-system]
requires = [
    "setuptools >=44",
    "packaging",
    "wheel >=0.36",
    "torch",
    "rascaline @ https://github.com/Luthaf/rascaline/archive/7c889b7ebb469ea91f424d81aed9bed80532c6f8.zip",
    "cmake",
]
build-backend = "setuptools.build_meta"

[tool.tox]
legacy_tox_ini = """
[tox]

[testenv]
skip_install = True
deps =
    discover
    ase
    torch
    rascaline @ https://github.com/Luthaf/rascaline/archive/7c889b7ebb469ea91f424d81aed9bed80532c6f8.zip

commands =
    python setup.py --quiet install
    discover -p "*.py" -s tests
"""
