[build-system]
requires = [
    "setuptools >=44",
    "wheel >=0.36",
    "torch >=1.9,<1.10",
    "rascaline @ https://github.com/Luthaf/rascaline/archive/a6f095af0ebd146535fa5b3b5e31bb65555b9f8e.zip",
    "cmake",
]
build-backend = "setuptools.build_meta"

[tool.tox]
legacy_tox_ini = """
[tox]

[testenv]
skip_install = True
deps =
    discover
    ase
    torch >=1.9,<1.10
    rascaline @ https://github.com/Luthaf/rascaline/archive/a6f095af0ebd146535fa5b3b5e31bb65555b9f8e.zip

commands =
    python setup.py --quiet install
    discover -p "*.py" -s tests
"""
